Hello_MIcroverse Project
Tushar151997/Hello_Microverse pull request #1
Opened 2022-09-21 14:38 UTC by Tushar151997

It's a simple project created using html and css .

2022-09-21 14:50 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @Tushar151997, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
 -  No linter errors. :heavy_check_mark: 
 -  Good README file. :heavy_check_mark: 
 -  Correct GiHub Flow. :heavy_check_mark: 
 -  Meaningful commit messages. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 14:50 UTC, Qoosim commented on .gitignore
> +MIT.md
- [OPTIONAL] Kindly remove MIT.md from your .gitignore file.

2022-09-21 14:50 UTC, Qoosim commented on README.md
> +## Authors
- [OPTIONAL] Kindly change this to singular  noun `Author`. This is a solo project and every solo project carries a single author.

2022-09-21 14:50 UTC, Qoosim commented on index.html
> +  <h1>Hello Micrverse</h1>
- [ ] Kindly give a class name to your `h1` element and use that class name to style the content of `h1` in your css file.

2022-09-21 14:50 UTC, Qoosim commented on style.css
> +}
- [ ] Kindly use the class name given to your `h1` element as a selector instead of using `h1` element as a selector. This is for semantics reason.

2022-09-23 09:31 UTC, Ugboaja-Uchechi approved these changes
Hi @Tushar151997 

## Status: APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 
- Great job with your design and functionalities 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 14:28 UTC, merged

2022-10-11 09:02 UTC, Tushar151997 commented
Hi Qoosim,

Hope you are doing well.

Could you please elaborate to me why using h1 tag instead of class name is
syntactically wrong . I don't think  there is anything wrong with it
because here I'm using a single h1 tag .
Sorry for opening a new pull request and I had done that because of a wrong
github account .

Kindly forgive me for that.

Regards,
Tushar

On Wed, Sep 21, 2022 at 8:21 PM Qoosim AbdulGhaniyy <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> *Status: Required Changes* ♻️
>
> Hi @Tushar151997 <https://github.com/Tushar151997>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
>    - No linter errors. ✔️
>    - Good README file. ✔️
>    - Correct GiHub Flow. ✔️
>    - Meaningful commit messages. ✔️
>
>
> <https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif>
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In .gitignore
> <https://github.com/Tushar151997/Hello_Microverse/pull/1#discussion_r976604828>
> :
>
> > \ No newline at end of file
>
> +node_modules
>
> +MIT.md
>
>
>
>    - [OPTIONAL] Kindly remove MIT.md from your .gitignore file.
>
> ------------------------------
>
> In README.md
> <https://github.com/Tushar151997/Hello_Microverse/pull/1#discussion_r976606431>
> :
>
> > +## Getting Started
>
> +
>
> +To get a local copy up and run git clone https://github.com/Tushar151997/Hello and follow these steps.
>
> +
>
> +
>
> +To get a local copy up and running follow these simple example steps.
>
> +
>
> +
>
> +### Open file in the VS code
>
> +
>
> +### Run the index.html file on any browser
>
> +
>
> +
>
> +
>
> +
>
> +## Authors
>
>
>
>    - [OPTIONAL] Kindly change this to singular noun Author. This is a
>    solo project and every solo project carries a single author.
>
> ------------------------------
>
> In index.html
> <https://github.com/Tushar151997/Hello_Microverse/pull/1#discussion_r976607690>
> :
>
> > @@ -0,0 +1,13 @@
>
> +<!DOCTYPE html>
>
> +<html lang="en">
>
> +<head>
>
> +  <meta charset="UTF-8">
>
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
>
> +  <meta name="viewport" content="width=device-width, initial-scale=1.0">
>
> +  <title>Document</title>
>
> +  <link rel="stylesheet" href="style.css">
>
> +</head>
>
> +<body>
>
> +  <h1>Hello Micrverse</h1>
>
>
>
>    - Kindly give a class name to your h1 element and use that class name
>    to style the content of h1 in your css file.
>
> ------------------------------
>
> In style.css
> <https://github.com/Tushar151997/Hello_Microverse/pull/1#discussion_r976609680>
> :
>
> > +h1 {
>
> +  color: aqua;
>
> +}
>
>
>
>    - Kindly use the class name given to your h1 element as a selector
>    instead of using h1 element as a selector. This is for semantics
>    reason.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Tushar151997/Hello_Microverse/pull/1#pullrequestreview-1115566118>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3CF5D5WLKMX5MRVJMLDLV3V7MOFLANCNFSM6AAAAAAQSEQNYE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>